version: "3"
services:
  mconf-aggr-webhook:
    image: mconf/mconf-aggr:webhook-latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    networks:
      - mconf-net
    env_file:
      - ${MCONF_AGGR_WEBHOOK_ENV_FILE}

  mconf-aggr-zabbix:
    image: mconf/mconf-aggr:zabbix-latest
    deploy:
      replicas: 0
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - mconf-net
    env_file:
      - ${MCONF_AGGR_ZABBIX_ENV_FILE}

networks:
  mconf-net:
